### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by dylnclrk** [carbonfive/raygun-rails#188]
I don't think there's any action items here, but I wanted to call this out just so there's a place to discuss. Just in case anyone else runs in to this…

When installing dependencies on a new project today, I see the post-install message:

```
Post-install message from sass:
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```

Digging in, it looks like the `sass` gem is a dependency of `sass-rails`. This dependency is removed in v6, but v6 is currently in beta.

I think `@dependabot[bot]` should take care of this once v6 is released and propagates through the web of dependencies.

**Comment by eskfung** [comment]
Interesting! It looks like `sassc-rails` has been in place [for a while](https://github.com/carbonfive/raygun-rails/pull/69), so I wonder where that message came from. I can confirm that I'm not seeing this deprecation warning anymore.

Good to close out?

**Comment by eskfung** [comment]
Oh, `rails new` will add `sass-rails` for you by default. 🤔
