### ISSUE TITLE
Generated app complains that phantomjs is not installed

### ISSUE THREAD

**Issue by mattbrictson** [carbonfive/raygun-rails#314]
We either need to document in the README that phantomjs is needed (with `brew` instructions for installing), or figure out how to remove the requirement. We are using Rails system tests with selenium-driven chromedriver, so phantomjs _shouldn't_ be needed.

/cc @spilth

**Comment by christiannelson** [comment]
I recommend switching to https://github.com/twalpole/apparition.

If you have access, check out https://github.com/carbonfive/candidate-tracker/pull/189 for how we switched that project to it.

**Comment by eskfung** [comment]
Any idea if this is still an issue? I generated an app and ran all tests, and didn't see this message.

**Comment by mattbrictson** [comment]
> Any idea if this is still an issue? I generated an app and ran all tests, and didn't see this message.

I think we can close it. The original issue might have been due to `raygun` generating a project from an old template. `raygun` generates from the latest tag of raygun-rails, and we hadn't updated the tag for a long time. The tag is now much more recent: https://github.com/carbonfive/raygun-rails/releases/tag/v1.6.1 (Jul 28 2020).
