### ISSUE TITLE
HOSTNAME conflicts with the same variable managed by Docker

### ISSUE THREAD

**Issue by mattbrictson** [carbonfive/raygun-rails#322]
We've run across some problems when a raygun-generated app is packaged and run via Docker. At runtime Docker will inject a `HOSTNAME` environment variable, which causes this canonical-redirect magic to get enabled:

https://github.com/carbonfive/raygun-rails/blob/f162ce0d07885b6901c2401d36b79bab2366ef8b/config.ru#L6

This is almost never what you want when developing locally. The developer will try to access the app via `http://localhost:3000` but that will get intercepted by a redirect to the Docker hostname, which doesn't connect. As a result the developer can't use the app. A workaround is to explicitly set `HOSTNAME=localhost rails s` to start the app, but this is cumbersome.

We could potentially fix this by renaming the variable to `RAILS_HOSTNAME` or `CANONICAL_HOSTNAME` to avoid the Docker conflict.

**Comment by christiannelson** [comment]
100% agree on a new name. My vote is for `CANONICAL_HOSTNAME`.
