### ISSUE TITLE
AbsoluteAssetPathError when running spec:javascipts

### ISSUE THREAD

**Issue by christiannelson** [carbonfive/raygun-rails#48]
This is a tricky one to describe, because it works in some cases and not others.

a) it work when run in conjunction with spring
b) it fails when spring is out of the picture, either via bundle exec or direct.

The issue is that the server that's started up to serve the js specs is running in development mode.

Removing better_errors and binding_of_caller yeilds a different error:

```
Jasmine runner at '/specs' returned a 500 error: Internal Server Error
```

Interestingly, I tried modeset/teaspoon out as an alternative to jasmine-rails, and it also has a very similar problem (see modeset/teaspoon/issues/197).

Related issues:  searls/jasmine-rails/issues/147 searls/jasmine-rails/issues/121

I consider raygun broken until we resolve this issue.

**Comment by christiannelson** [comment]
This is what rspec does to switch into test mode, even though rake itself is invoked in development mode: https://github.com/rspec/rspec-rails/blob/master/lib/rspec/rails/tasks/rspec.rake#L23

**Comment by ingar** [comment]
If you run any specs using spring (using bin/rake, direnv or whatever), the spring-commands-rspec gem is picking up the rake task and starting the app in the test environment.  When you run it without spring, it runs in development by default and you which has `config.assets.raise_runtime_errors = true` and throws the error. You can get around this with `RAILS_ENV=test rake spec`.

**Comment by searls** [comment]
Hey @christiannelson, now that searls/jasmine-rails#173 is merged, is this a problem? I worry that it might be if this issue comes up when you're running `rails s` and hitting `/specs` in the browser.

**Comment by christiannelson** [comment]
@searls Thanks for asking! I haven't tried running the specs in the browser... when I do I'll report any issues (if any). The latest version gets around the original assets issue. Though, I'm seeing some slightly odd behavior in raygun-rails... might be something we're doing though.

What happens is that when jasmine specs are run, it systems out, then re-runs our rspec specs before getting to the jasmine specs.

We're redefining the default behavior for rake here: https://github.com/carbonfive/raygun-rails/blob/master/Rakefile#L10-L11

And spec is defined here: https://github.com/carbonfive/raygun-rails/blob/master/lib/tasks/spec.rake#L21-L22

Something about that is triggering a rerun of `spec:without_features` and `spec:features`.

We'll look into it let you know if there's anything noteworthy about jasmine-rails.

/cc @rudyjahchan

**Comment by searls** [comment]
Hmm, that's interesting. Yeah, since it's shelling out to whatever is in ARGV, if you run `rake`, and your default `spec` task depends on rspec and jasmine, then what that `system` call will really be doing is redoing everything. That's not good.

Not sure how I'd solve that but it's definitely a valid issue. Please open an issue on jasmine-rails
