### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by keathley** [carbonfive/raygun-rails#51]
What do y'all think about adding something like https://github.com/ai/autoprefixer-rails?  I'm using it on two different Raygun generated apps and it's been working great.  Takes a lot of the pain out of vendor prefixing without needing a set or sass mixins or similar solution.  If it's something thats worth pursuing then I'm happy to submit a PR.

**Comment by keathley** [comment]
Realized that this issue is better suited [here](https://github.com/carbonfive/raygun/issues/131)

**Comment by christiannelson** [comment]
@keathley Actually, this is the right repo for the question. `raygun` is the gem, but it doesn't dictate anything about the contents of the generated project, all of that is in `raygun-rails`.

**Comment by christiannelson** [comment]
This looks good to me. One question: has anyone notice an impact on asset pipeline performance?

**Comment by keathley** [comment]
I haven't noticed any issues in development yet.  If it became a problem we could look at disabling it in development mode.

**Comment by mwean** [comment]
:+1: This is key and I also haven't noticed any slowness

**Comment by christiannelson** [comment]
Let's do it. Anyone want to put together a PR?

**Comment by keathley** [comment]
I can handle it here in a bit



Chris Keathley
