### ISSUE TITLE
bump puma to avoid dead threads from hanging around

### ISSUE THREAD

**Issue by bunnymatic** [carbonfive/raygun-rails#54]
In a recent update to puma, there was a fix that improved the reaping of dead threads.
https://github.com/puma/puma/issues/691

we recently deployed a fairly simple app with low traffic that was running into memory issues on Heroku.  You can see what looks to be a pretty leaky something (as memory usage increases over time), but the timing for this was overnight with very very little traffic.  

I'm going to try Puma 2.12.3 (latest as of today) and see if that helps.  If so, I might recommend bumping puma in the Gemfile lock so that a new project starts off without that issue.

Maybe nothing to do yet, but thought i'd file an issue, in case others may have reports that can corroborate or debunk this theory.

More as it happens

**Comment by christiannelson** [comment]
Bumped puma and all of the other dep in 18379e17a94a639986ca042366fac128e997fcd7.

**Comment by bunnymatic** [comment]
Though we had other performance issues with the app, this appeared to make our memory profile a bit more stable over time.

I guess we can close this one.
