### ISSUE TITLE
Adopt `good_migrations`

### ISSUE THREAD

**Issue by jonah-williams** [carbonfive/raygun-rails#65]
https://github.com/testdouble/good-migrations should fix a common source of breaking migrations by disabling autoloading app code during migrations.

How many times have we hit an app which can no longer be migrated from scratch to setup a clean development environment because a migration references a deleted model? How about migrations with unexpected side effects when model observers fire during the migration?

You'll have to redefine models in each migration but I think that's a practice Rails apps should be following anyway; a migration should act on a snapshot of (a subset of) the model as it existed at the time the migration was written.

Disclaimer: I've been away from Rails work too long and haven't used the gem yet so there are probably concerns I'm not thinking of (maybe monkey patching is too fragile?). I just remember troubleshooting this too many times so I'm happy to see an automated solution.

**Comment by christiannelson** [comment]
Thanks for the issue Jonah! :)

I almost completely agree with the best practices here, but prefer to resolve the issue with education, rather than adding another gem.
